### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hardware** [samarudge/dnsyo#20]
Hi,

I got this error during installation with pip :

```
pip install dnsyo

Collecting dnsyo
  Using cached dnsyo-2.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-q0yv15hs/dnsyo/setup.py", line 36, in <module>
        if sys.version[:2] <= [2, 6]:
    TypeError: unorderable types: str() <= list()
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q0yv15hs/dnsyo
```

Any ideas ?

**Comment by samarudge** [comment]
Hey,

What version of python are you running? (`python --version`)

**Comment by hardware** [comment]
Python 3.4.3

**Comment by samarudge** [comment]
Ahh ok, the current version doesn't support Python3 right now, but I'm working on a branch that does. Waiting for all the builds to pass in #21

**Comment by hardware** [comment]
Ok no problem, i will wait :)

**Comment by samarudge** [comment]
Fixed in 2.0.7 https://pypi.python.org/pypi/dnsyo/2.0.7

Try installing again and let me know how you get on

**Comment by samarudge** [comment]
(Since it's a failed install you might have to do `pip install dnsyo --upgrade`)

**Comment by hardware** [comment]
Well done, it's working ! 

```
dnsyo -t 100 -q ALL meshup.net

INFO:root:Updating resolver list file
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.codesam.co.uk
Status: Queried 1097 of 1097 servers, duration: 0:00:14.936613

 - RESULTS

I asked 1097 servers for A records related to meshup.net,
887 responded with records and 210 gave errors
Here are the results;


886 servers responded with;
37.59.39.91

1 servers responded with;
217.16.223.110



And here are the errors;


32 servers responded with;
No Answer

13 servers responded with;
No Nameservers

165 servers responded with;
Server Timeout
```

Tkanks :smiley:
